defaults:
  - base
  - override dataset: cityscapes
  - _self_

# Evaluation settings
eval:
  task: "seg"
  model_ckpt: null 

num_epochs: 20

optimizer: 
  lr: 5e-4

train_dataloader:
  batch_size: 2

val_dataloader:
  batch_size: 1

img_size: 448
target_size: ${img_size}

# Metrics settings
metrics:
  seg:
    num_classes: ${dataset.num_classes}
    
sanity: false